module.exports={
    USER_COLLECTION:"users",
    ADMIN_COLLECTION:"admin",
    OTP_COLLECTION:"emailotp",
    POST_COLLECTION:"posts",
    ONLINE_USERS_COLLECTION:"onlineUsers",
    COMMENT_COLLECTION:'comments',
    REPORTS_COLLECTION:'reports',
    NOTIFICATIONS_COLLECTION:'notifications',
    TOKEN_COLLECTION:'token'
}